# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs: # a basic unit of work in a run
  ios-test:
    macos:
      xcode: 13.3
    steps:
      - checkout 
      - run:
          name: Add VNC user
          command: sudo /usr/sbin/sysadminctl -addUser vncuser -fullName "rudrank" -password "codemagic" -admin
      - run:
          name: Run Tests
          command: xcodebuild -project Quoty.xcodeproj -scheme "Quoty-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4' test
  macos-test:
    macos:
      xcode: 13.3
    steps:
      - checkout
      - run:
          name: Add VNC user
          command: sudo /usr/sbin/sysadminctl -addUser vncuser -fullName "rudrank" -password "codemagic" -admin
      - run:
          name: Run Tests
          command: xcodebuild test -scheme "Quoty-macOS"

workflows:
  ios-testing-workflow:
    jobs:
      - ios-test
  macos-testing-workflow:
    jobs:
      - macos-test 